#version: "3.9"

services:
  ingest:
    build:
      context: .
      dockerfile: docker/Dockerfile.ingest
    container_name: ingest_container
    volumes:
      - ./data/raw:/app/raw
      - ./data/samples:/app/samples
      - ./logs/ingest:/app/logs
    env_file:
      - .env
    networks:
      - ml-network

  etl:
    build:
      context: .
      dockerfile: docker/Dockerfile.etl
    container_name: etl_container
    volumes:
      - ./data/raw:/app/raw
      - ./data/processed:/app/processed
      - ./data/samples:/app/samples
      - ./logs/etl:/app/logs
    depends_on:
      - ingest
    env_file:
      - .env
    networks:
      - ml-network

  training:
    build:
      context: .
      dockerfile: docker/Dockerfile.training
    container_name: training_container
    volumes:
      - ./data/processed:/app/processed
      - ./models:/app/models
      - ./logs/training:/app/logs
    depends_on:
      - etl
    env_file:
      - .env
    networks:
      - ml-network

  front:
    build:
      context: .
      dockerfile: docker/Dockerfile.front
    container_name: front_container
    ports:
      - "8501:8501"
    volumes:
      - ./data/processed:/app/processed
      - ./models:/app/models
      - ./logs/front:/app/logs
    depends_on:
      - etl
      - training
    env_file:
      - .env
    networks:
      - ml-network

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: api_container
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs/api:/app/logs
    restart: always
    depends_on:
      - ingest
      - etl
      - training
    env_file:
      - .env
    networks:
      - ml-network

  serving:
    build:
      context: .
      dockerfile: docker/Dockerfile.serving
    container_name: serving_container
    ports:
      - "8001:8000"   # host:container (évite conflit avec api:8000)
    volumes:
      - ./models:/app/models
      - ./logs/serving:/app/logs
    restart: always
    depends_on:
      - training
    env_file:
      - .env
    networks:
      - ml-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health').read()"]
      interval: 10s
      timeout: 3s
      retries: 10
    environment:
      - SERVING_API_KEY=${SERVING_API_KEY}

  tester:
    image: python:3.12-slim
    container_name: serving_tester
    depends_on:
      serving:
        condition: service_healthy
    volumes:
      - ./scripts:/scripts
    working_dir: /scripts
    command: >
      sh -c "pip install --no-cache-dir requests && python shadow_test.py"
    environment:
      - BASE_URL=http://serving:8000
      - SERVING_API_KEY=${SERVING_API_KEY}
    networks:
      - ml-network

networks:
  ml-network:
    driver: bridge
