version: "3.9"

services:
  ingest:
    build:
      context: .
      dockerfile: docker/Dockerfile.ingest
    container_name: ingest_container
    volumes:
      - ./data/raw:/app/raw
      - ./data/samples:/app/samples
      - ./logs/ingest:/app/logs
    env_file:
      - .env
      - .env.aws
    networks:
      - ml-network

  etl:
    build:
      context: .
      dockerfile: docker/Dockerfile.etl
    container_name: etl_container
    volumes:
      - ./data/raw:/app/raw
      - ./data/processed:/app/processed
      - ./data/samples:/app/samples
      - ./logs/etl:/app/logs
    depends_on:
      - ingest
    env_file:
      - .env
    networks:
      - ml-network

  training:
    build:
      context: .
      dockerfile: docker/Dockerfile.training
    container_name: training_container
    volumes:
      - ./data/processed:/app/processed
      - ./models:/app/models
      - ./logs/training:/app/logs
    depends_on:
      - etl
    env_file:
      - .env
    networks:
      - ml-network

  front:
    build:
      context: .
      dockerfile: docker/Dockerfile.front
    container_name: front_container
    ports:
      - "8501:8501"
    volumes:
      - ./data/processed:/app/processed
      - ./models:/app/models
      - ./logs/front:/app/logs
    depends_on:
      - etl
      - training
    env_file:
      - .env
    networks:
      - ml-network

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: api_container
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs/api:/app/logs
    restart: always
    depends_on:
      - ingest
      - etl
      - training
    env_file:
      - .env
    networks:
      - ml-network

networks:
  ml-network:
    driver: bridge
