FROM python:3.12-slim

WORKDIR /app

COPY docker/requirements/requirements.front.txt .
RUN pip install --no-cache-dir -r requirements.front.txt

# Copier uniquement le code nécessaire pour l’UI et les utils
COPY frontend/ ./frontend/
COPY src/utils/ ./src/utils/

# Créer dossiers pour données et modèles
RUN mkdir -p /app/processed /app/models /app/logs

EXPOSE 8501

CMD ["streamlit", "run", "frontend/app_front.py", "--server.port=8501", "--server.address=0.0.0.0"]
