FROM python:3.12-slim

WORKDIR /app

COPY docker/requirements/requirements.etl.txt .
RUN pip install --no-cache-dir -r requirements.etl.txt

COPY src/etl/ ./src/etl/
COPY src/utils/ ./src/utils/
COPY app.py .

RUN mkdir -p /app/raw /app/processed /app/samples /app/logs

CMD ["python", "app.py", "--mode", "etl"]
