FROM python:3.12-slim

WORKDIR /app

COPY docker/requirements/requirements.training.txt .
RUN pip install --no-cache-dir -r requirements.training.txt

COPY src/training/ ./src/training/
COPY src/utils/ ./src/utils/
COPY app.py .

RUN mkdir -p /app/processed /app/models /app/logs

CMD ["python", "app.py", "--mode", "training"]
